# Generated by Django 4.2.6 on 2023-12-02 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sViajes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marca',
            old_name='precioKM',
            new_name='precio_km',
        ),
        migrations.RenameField(
            model_name='marca',
            old_name='tiempoKm',
            new_name='tiempo_km',
        ),
        migrations.RenameField(
            model_name='sviaje',
            old_name='cantPersonas',
            new_name='cant_personas',
        ),
        migrations.RenameField(
            model_name='sviaje',
            old_name='recogidaDate',
            new_name='recogida_date',
        ),
        migrations.RenameField(
            model_name='sviaje',
            old_name='reservaDate',
            new_name='reserva_date',
        ),
    ]
