# Generated by Django 4.2.6 on 2023-12-06 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sViajes', '0003_alter_cliente_nombre_alter_taxi_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
