# Generated by Django 4.2.6 on 2023-12-07 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sViajes', '0005_remove_viajefactura_factura_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=7)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sViajes.cliente', verbose_name='Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='ViajeFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sViajes.factura', verbose_name='Factura')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sViajes.sviaje', verbose_name='Viaje')),
            ],
        ),
    ]
